version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      - 25565:25565
    environment:
      - EULA:TRUE
      - MEMORY:6G
      - TYPE:CURSEFORGE
      - CF_SERVER_MOD:Valhelsia_3-3.2.4.zip
      - SERVER_NAME:"${SERVER_NAME}"
      - MOTD:"${MOTD}"
      - WHITELIST:"${WHITELIST}"
      - OPS:"${OPS}"
      - ICON:https://multidoge.org/images/MultiDoge.png
    volumes:
    - ./data:/data
